var searchData=
[
  ['readadcvalue_5fserial_5fmultiplesensor_189',['ReadADCValue_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ad02956f6d6dc7f652a3d7acdcfd66f3d',1,'ReadADCValue_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *ADC_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#ae626e0ac371e4e16a84f0f1d78b28e1b',1,'ReadADCValue_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *ADC_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readcounterscalib_5fserial_5fmultiplesensor_190',['ReadCountersCalib_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ab6fde4b7920e31dc3f73f19e4a78c141',1,'ReadCountersCalib_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, float *C0_ptr, float *C1_ptr, float *C2_ptr, float *C3_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a8a225936289e689cbaaf364f7d4ee5c8',1,'ReadCountersCalib_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, float *C0_ptr, float *C1_ptr, float *C2_ptr, float *C3_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readcountersmeasurements_5fserial_5fmultiplesensor_191',['ReadCountersMeasurements_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ad34aa848a26f565708702fc54ce70f85',1,'ReadCountersMeasurements_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *counters_measurements_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a2b3c30b2320c5136badbcb3f769b87b6',1,'ReadCountersMeasurements_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *counters_measurements_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readfrequencymeasurement_5fserial_5fmultiplesensor_192',['ReadFrequencyMeasurement_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a60a12d27c753acfcb168d1e9332702d8',1,'ReadFrequencyMeasurement_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int32_t *integer_CH_vector):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#af98546f5f458fff9e46ff74b075f4289',1,'ReadFrequencyMeasurement_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int32_t *integer_CH_vector):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readheadercalibtable_5fserial_5fmultiplesensor_193',['ReadHeaderCalibTable_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ab150fb0983aa095983c6bbeb02cbe41c',1,'ReadHeaderCalibTable_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, unsigned char *calib_table_is_active_bool_ptr, unsigned char *number_table_lines_ptr, unsigned char *calibration_mode_multi_or_single_ch_ptr, char *jumper_selection_osc_tunning_range_ptr, char *units_str_ptr, char *counter_calib_units_str_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#aa1c43868dcb824f5a5a6850b387f027c',1,'ReadHeaderCalibTable_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, unsigned char *calib_table_is_active_bool_ptr, unsigned char *number_table_lines_ptr, unsigned char *calibration_mode_multi_or_single_ch_ptr, char *jumper_selection_osc_tunning_range_ptr, char *units_str_ptr, char *counter_calib_units_str_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readlinecalibtable_5fserial_5fmultiplesensor_194',['ReadLineCalibTable_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a3ec0d93f6b678c42af88eda9f3715420',1,'ReadLineCalibTable_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, int line_number, float *RAW_value_ptr, float *measurement_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a6a33ad9a75b15ce1c4936ebcefa90295',1,'ReadLineCalibTable_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int channel_number, int line_number, float *RAW_value_ptr, float *measurement_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readmeasurements_5fserial_5fmultiplesensor_195',['ReadMeasurements_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ad22a20ced3a2eef6c7d7e402e3eaf86f',1,'ReadMeasurements_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *measurements_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#af6690cbf7f6de2f31fcce294c6713cbd',1,'ReadMeasurements_Serial_MultipleSensor(MultipleSensor_serial_driver *session, float *measurements_values_vector_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readmodechconfig_5fserial_5fmultiplesensor_196',['ReadModeCHConfig_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#afd4042fd997ad2d634fb779213d09976',1,'ReadModeCHConfig_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char *mode_is_single_channel_bool_ptr, int *selected_channel_number_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a27c14d669dd9fb6c3b90b4ee9b56b948',1,'ReadModeCHConfig_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char *mode_is_single_channel_bool_ptr, int *selected_channel_number_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readoutputconfig_5fserial_5fmultiplesensor_197',['ReadOutputConfig_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a16670947b8e9cdbed6ebae7c80cecda9',1,'ReadOutputConfig_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char output_number, char *out_bool_func_str):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a45c6171df43abb99afb46fd9e4ebabe9',1,'ReadOutputConfig_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char output_number, char *out_bool_func_str):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readoutputs_5fserial_5fmultiplesensor_198',['ReadOutputs_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#ae682185324fb83b236b4b830061ad1fb',1,'ReadOutputs_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char *outputs_vector):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a99f8b94b9c5a967de60a7538b94e13e9',1,'ReadOutputs_Serial_MultipleSensor(MultipleSensor_serial_driver *session, unsigned char *outputs_vector):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readsensorconfigs_5fserial_5fmultiplesensor_199',['ReadSensorConfigs_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a24174e2b1a767d84f172136d32e4c394',1,'ReadSensorConfigs_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int configs_for_channel_number, char *make_compare_w_calibrated_sensor_value_ptr, char *compare_is_greater_than_ptr, char *sensor_prescaler_ptr, char *sensor_used_for_OUT_ptr, float *sensor_trigger_value_ptr):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#ade3637aa2c2726886a272fdc5d5fa3f5',1,'ReadSensorConfigs_Serial_MultipleSensor(MultipleSensor_serial_driver *session, int configs_for_channel_number, char *make_compare_w_calibrated_sensor_value_ptr, char *compare_is_greater_than_ptr, char *sensor_prescaler_ptr, char *sensor_used_for_OUT_ptr, float *sensor_trigger_value_ptr):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['readsensorcounters_5fserial_5fmultiplesensor_200',['ReadSensorCounters_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a065c7225392e868d2a9fbad9dce08a63',1,'ReadSensorCounters_Serial_MultipleSensor(MultipleSensor_serial_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#ab11b42c12f36273cc0666bca096f6373',1,'ReadSensorCounters_Serial_MultipleSensor(MultipleSensor_serial_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_modbus_driver.cpp']]],
  ['removechar_201',['RemoveChar',['../multiple__sensor__modbus__driver_8cpp.html#a3027a638aa74d1d2997edbe45139c6f6',1,'multiple_sensor_modbus_driver.cpp']]],
  ['resetsensorcounters_5fserial_5fmultiplesensor_202',['ResetSensorCounters_Serial_MultipleSensor',['../multiple__sensor__modbus__driver_8cpp.html#a387f40d8ef316c195bc287892d5027db',1,'ResetSensorCounters_Serial_MultipleSensor(MultipleSensor_serial_driver *session):&#160;multiple_sensor_modbus_driver.cpp'],['../multiple__sensor__modbus__driver_8h.html#a3ef6eb690c52e3b0772700acec3fd124',1,'ResetSensorCounters_Serial_MultipleSensor(MultipleSensor_serial_driver *session):&#160;multiple_sensor_modbus_driver.cpp']]]
];
