var searchData=
[
  ['readadcvalue_5fusb_5fmultiplesensor_88',['ReadADCValue_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a23dba9479a3a41dcb2796043f021af24',1,'ReadADCValue_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *ADC_values_vector_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a1330f3d9d01c6c12f262faba1e6fd06e',1,'ReadADCValue_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *ADC_values_vector_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readcounterscalib_5fusb_5fmultiplesensor_89',['ReadCountersCalib_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a677fc0f153b7901232dce95cf8610185',1,'ReadCountersCalib_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, float *C0_ptr, float *C1_ptr, float *C2_ptr, float *C3_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a2d1a16dbc3f3f34a87cdd98a8f14326d',1,'ReadCountersCalib_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, float *C0_ptr, float *C1_ptr, float *C2_ptr, float *C3_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readcountersmeasurements_5fusb_5fmultiplesensor_90',['ReadCountersMeasurements_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a92a9be44d9f92cc3af6494420c81c9c3',1,'ReadCountersMeasurements_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *counters_measurements_values_vector_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a7ec6e5d413504a079f55ef0f691b37cb',1,'ReadCountersMeasurements_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *counters_measurements_values_vector_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readfrequencymeasurement_5fusb_5fmultiplesensor_91',['ReadFrequencyMeasurement_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#aa62e8d3361eb45a3ff4ae88ba29752ad',1,'ReadFrequencyMeasurement_USB_MultipleSensor(MultipleSensor_USB_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a47e168b825d3544ec11c4f0868797c51',1,'ReadFrequencyMeasurement_USB_MultipleSensor(MultipleSensor_USB_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_usb_driver.c']]],
  ['readheadercalibtable_5fusb_5fmultiplesensor_92',['ReadHeaderCalibTable_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a19b6333b1f89dc3c7460dff86898cddf',1,'ReadHeaderCalibTable_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, unsigned char *calib_table_is_active_bool_ptr, unsigned char *number_table_lines_ptr, unsigned char *calibration_mode_multi_or_single_ch_ptr, char *jumper_selection_osc_tunning_range_ptr, char *units_str_ptr, char *counter_calib_units_str_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#add410ed6ea7a748ad42b346b9871b2ea',1,'ReadHeaderCalibTable_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, unsigned char *calib_table_is_active_bool_ptr, unsigned char *number_table_lines_ptr, unsigned char *calibration_mode_multi_or_single_ch_ptr, char *jumper_selection_osc_tunning_range_ptr, char *units_str_ptr, char *counter_calib_units_str_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readlinecalibtable_5fusb_5fmultiplesensor_93',['ReadLineCalibTable_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a8ad0c47d38942be64ccafa8af05b6da7',1,'ReadLineCalibTable_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, int line_number, float *RAW_value_ptr, float *measurement_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a693e35b59950b3a4770d145f1cc52898',1,'ReadLineCalibTable_USB_MultipleSensor(MultipleSensor_USB_driver *session, int channel_number, int line_number, float *RAW_value_ptr, float *measurement_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readmeasurements_5fusb_5fmultiplesensor_94',['ReadMeasurements_USB_MultipleSensor',['../multiple__sensor__usb__driver_8h.html#a7a6db432cbd25fd02e62a1f1eee14ee7',1,'ReadMeasurements_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *measurements_vector_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8c.html#a3fa59381f04dbefcc5c0e36e267966ed',1,'ReadMeasurements_USB_MultipleSensor(MultipleSensor_USB_driver *session, float *measurements_vector_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readmodechconfig_5fusb_5fmultiplesensor_95',['ReadModeCHConfig_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#ac97ee0264f347a6644d78ee5149d21d6',1,'ReadModeCHConfig_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char *mode_is_single_channel_bool_ptr, int *selected_channel_number_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a806f123a6d0ea63d9cd2e7306281bfe8',1,'ReadModeCHConfig_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char *mode_is_single_channel_bool_ptr, int *selected_channel_number_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readoutputconfig_5fusb_5fmultiplesensor_96',['ReadOutputConfig_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#afe6fd5322f81e0fc5885aaa48700073e',1,'ReadOutputConfig_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char output_number, char *out_bool_func_str):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#ac89e6ea9a576ddecb15fdd9c95a3cc2a',1,'ReadOutputConfig_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char output_number, char *out_bool_func_str):&#160;multiple_sensor_usb_driver.c']]],
  ['readoutputs_5fusb_5fmultiplesensor_97',['ReadOutputs_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#aaa88628db534fd4fb4830a4e27d67e55',1,'ReadOutputs_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char *outputs_vector):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#ae31a1f8b204fd67d0a1e4b0a228afbdb',1,'ReadOutputs_USB_MultipleSensor(MultipleSensor_USB_driver *session, unsigned char *outputs_vector):&#160;multiple_sensor_usb_driver.c']]],
  ['readsensorconfigs_5fusb_5fmultiplesensor_98',['ReadSensorConfigs_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a1fb33b390da55afd7164f1125f93aea5',1,'ReadSensorConfigs_USB_MultipleSensor(MultipleSensor_USB_driver *session, int configs_for_channel_number, char *make_compare_w_calibrated_sensor_value_ptr, char *compare_is_greater_than_ptr, char *sensor_prescaler_ptr, char *sensor_used_for_OUT_ptr, float *sensor_trigger_value_ptr):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a60b2f78cdfb7ce2a4bbc999b1cb17b0e',1,'ReadSensorConfigs_USB_MultipleSensor(MultipleSensor_USB_driver *session, int configs_for_channel_number, char *make_compare_w_calibrated_sensor_value_ptr, char *compare_is_greater_than_ptr, char *sensor_prescaler_ptr, char *sensor_used_for_OUT_ptr, float *sensor_trigger_value_ptr):&#160;multiple_sensor_usb_driver.c']]],
  ['readsensorcounters_5fusb_5fmultiplesensor_99',['ReadSensorCounters_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#a92ca9b43f195f6c57715aa4c9c1ca002',1,'ReadSensorCounters_USB_MultipleSensor(MultipleSensor_USB_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#aac57740c4864c8b5cb96e9760f6d6f39',1,'ReadSensorCounters_USB_MultipleSensor(MultipleSensor_USB_driver *session, long int *integer_CH_vector):&#160;multiple_sensor_usb_driver.c']]],
  ['reg_5fstarting_5faddress_100',['reg_starting_address',['../struct_modbus___data___struct.html#a4b17a47396f1f8b43c610afe123930b0',1,'Modbus_Data_Struct']]],
  ['removechar_101',['RemoveChar',['../multiple__sensor__usb__driver_8c.html#a3027a638aa74d1d2997edbe45139c6f6',1,'multiple_sensor_usb_driver.c']]],
  ['reset_5fmultiple_5fsensor_5fcounter_5fvalues_5fcode_5fmodbusrtu_102',['RESET_MULTIPLE_SENSOR_COUNTER_VALUES_CODE_ModbusRTU',['../multiple__sensor__usb__driver_8c.html#aaaa45e5ffb0211e3155c15a3c93e4cdb',1,'multiple_sensor_usb_driver.c']]],
  ['reset_5fmultiple_5fsensor_5fcounter_5fvalues_5fmodbusrtu_5ffunction_103',['RESET_MULTIPLE_SENSOR_COUNTER_VALUES_ModbusRTU_Function',['../multiple__sensor__usb__driver_8c.html#a7dfe2f375e0cfe3da16c47a94ea820a8',1,'multiple_sensor_usb_driver.c']]],
  ['resetsensorcounters_5fusb_5fmultiplesensor_104',['ResetSensorCounters_USB_MultipleSensor',['../multiple__sensor__usb__driver_8c.html#ae7e10c68baad4163f94521d0c6703f4b',1,'ResetSensorCounters_USB_MultipleSensor(MultipleSensor_USB_driver *session):&#160;multiple_sensor_usb_driver.c'],['../multiple__sensor__usb__driver_8h.html#a37e953be7a085f4edbbada7fedf88249',1,'ResetSensorCounters_USB_MultipleSensor(MultipleSensor_USB_driver *session):&#160;multiple_sensor_usb_driver.c']]],
  ['ret_5ftype1_105',['ret_type1',['../multiple__sensor__usb__driver_8c.html#a45aa2a32122670ea834079701b77c4fb',1,'multiple_sensor_usb_driver.c']]],
  ['ret_5ftype1_5fstruct_106',['ret_type1_struct',['../structret__type1__struct.html',1,'']]],
  ['ret_5fvalue_107',['ret_value',['../structret__type1__struct.html#aabe89482a17bf30a40e9c316bc5a2bb9',1,'ret_type1_struct']]]
];
